### ISSUE TITLE
Praise

### ISSUE THREAD

**Issue by skreutzberger** [wobsoriano/solid-firebase#10]
Hi,

I just wanted to give praise and applause for this great open-source project! I am currently migrating a complex app which uses Nextjs + React + Firebase Auth to Astro + Solidjs and your project helped a lot! It is shocking how small the footprint is in terms of kilobyte to download. 

Thanks a lot and please keep the project as lean and small as possible (modularized?) because at least in my use case the reason to move from React to Solid was to stop having these super huge Javascript codebases a frontend has to download.

So thanks again and feel free to close the issue since it is not an issue 😬❤️

**Comment by wobsoriano** [comment]
Thank you! I appreciate it.
