### ISSUE TITLE
Error for using pnpm package

### ISSUE THREAD

**Issue by kirill-dev-pro** [wobsoriano/solid-firebase#6]
I'm getting init error in project that firebase app 'DEFAULT' is initialized, call initializeApp etc. from the basic example of usage firebase/auth
I tried to debug it and copied source files from your project directly and error disappear. Probably it is something with how package manager work with contexts in your package but dont know actually

**Comment by wobsoriano** [comment]
Thanks for reporting! it would be nice if you could share a simple repro.

**Comment by Marvosg** [comment]
Hi, nice library :) I'm facing the same issue. Here is a reproduction: https://github.com/Marvosg/solid-firebase-error-default-app

**Comment by Tim4497** [comment]
Same for me, I don#t know how this Provider thing works but I just added:
```
const app = initializeApp(firebaseConfig);
const db = getFirestore(app);
```
to my App Component

**Comment by wobsoriano** [comment]
Fixed documentation. Thanks!
